
enum SIMULATE_STATE {
	START = 4000,
	STOP = 4001,
	IMMEDIATELY = 4002,
}

enum GEOMETRY_TYPE {
	NULL = 1000,
	SPHERE = 1001,
	BOX = 1002,
	CYLINDER = 1003,
	CONE = 1004,
	CAPSULE = 1005,
	CONVEX_HULL = 1006,
	TERRAIN = 1007,
}
enum JOINT_TYPE {
	NULL = 2000,
	SPHERICAL = 2001,
	REVOLUTE = 2002,
	CYLINDRICAL = 2003,
	PRISMATIC = 2004,
	UNIVERSAL = 2005,
	RAG_DOLL = 2006,
	GENERIC = 2007,
}
enum RIGID_BODY_TYPE {
	DYNAMIC = 3000,
	STATIC = 3001,
	KINEMATIC = 3002,
}
enum BROAD_PHASE_TYPE {
	NULL = 5000,
	BRUTE_FORCE = 5001,
	BVH = 5002,
}

enum BVH_INSERTION_STRATEGY {
	SIMPLE = 0,
	MINIMIZE_SURFACE_AREA = 1,
}

enum EPA_POLYHEDRON_STATE {
	OK = 0,
	INVALID_TRIANGLE = 1,
	NO_ADJACENT_PAIR_INDEX = 2,
	NO_ADJACENT_TRIANGLE = 3,
	EDGE_LOOP_BROKEN = 4,
	NO_OUTER_TRIANGLE = 5,
	TRIANGLE_INVISIBLE = 6,
}

enum GJK_EPA_RESULT_STATE {
	SUCCEEDED = 0,
	GJK_FAILED_TO_MAKE_TETRAHEDRON = 1,
	GJK_DID_NOT_CONVERGE = 2,
	EPA_FAILED_TO_INIT = 257,
	EPA_FAILED_TO_ADD_VERTEX = 258,
	EPA_DID_NOT_CONVERGE = 259,
}
enum POSITION_CORRECTION_ALGORITHM {
	BAUMGARTE = 0,
	SPLIT_IMPULSE = 1,
	NGS = 2,
}
enum JACOBIAN_ROW_BIT {
	LINEAR_SET = 1,
	ANGULAR_SET = 2,
}
enum CONSTRAINT_SOLVER_TYPE {
	ITERATIVE = 0,
	DIRECT = 1,
}


const CONSTANT = {

	BOX_BOX_DETECTOR_EDGE_BIAS_MULT: 1,

	EPA_TRIANGLE_COUNT: 0,
	VEC3_NUM_CREATIONS: 0,

	SETTING_DEFAULT_FRICTION: 0.2,
	SETTING_DEFAULT_RESTITUTION: 0.2,
	SETTING_DEFAULT_DENSITY: 1,
	SETTING_DEFAULT_COLLISION_GROUP: 1,
	SETTING_DEFAULT_COLLISION_MASK: 1,
	SETTING_MAX_TRANSLATION_PER_STEP: 20,
	SETTING_MAX_ROTATION_PER_STEP: 3.14159265358979,
	SETTING_BVH_PROXY_PADDING: 0.1,
	SETTING_BVH_INCREMENTAL_COLLISION_THRESHOLD: 0.45,
	SETTING_DEFAULT_GJK_MARGIN: 0.05,
	SETTING_ENABLE_GJK_CACHING: true,
	SETTING_MAX_EPA_VERTICES: 128,
	SETTING_MAX_EPA_POLYHEDRON_FACES: 128,
	SETTING_CONTACT_ENABLE_BOUNCE_THRESHOLD: 0.5,
	SETTING_VELOCITY_BAUMGARTE: 0.2,
	SETTING_POSITION_SPLIT_IMPULSE_BAUMGARTE: 0.4,
	SETTING_POSITION_NGS_BAUMGARTE: 1.0,
	SETTING_CONTACT_USE_ALTERNATIVE_POSITION_CORRECTION_ALGORITHM_DEPTH_THRESHOLD: 0.05,
	SETTING_DEFAULT_CONTACT_POSITION_CORRECTION_ALGORITHM: 0,
	SETTING_ALTERNATIVE_CONTACT_POSITION_CORRECTION_ALGORITHM: 1,
	SETTING_CONTACT_PERSISTENCE_THRESHOLD: 0.05,
	SETTING_MAX_MANIFOLD_POINTS: 4,
	SETTING_DEFAULT_JOINT_CONSTRAINT_SOLVER_TYPE: 0,
	SETTING_DEFAULT_JOINT_POSITION_CORRECTION_ALGORITHM: 0,
	SETTING_JOINT_WARM_STARTING_FACTOR_FOR_BAUNGARTE: 0.8,
	SETTING_JOINT_WARM_STARTING_FACTOR: 0.95,
	SETTING_MIN_SPRING_DAMPER_DAMPING_RATIO: 1E-6,
	SETTING_MIN_RAG_DOLL_MAX_SWING_ANGLE: 1E-6,
	SETTING_MAX_JACOBIAN_ROWS: 6,
	SETTING_DIRECT_MLCP_SOLVER_EPS: 1E-9,
	SETTING_ISLAND_INITIAL_RIGID_BODY_ARRAY_SIZE: 128,
	SETTING_ISLAND_INITIAL_CONSTRAINT_ARRAY_SIZE: 128,
	SETTING_SLEEPING_VELOCITY_THRESHOLD: 0.2,
	SETTING_SLEEPING_ANGULAR_VELOCITY_THRESHOLD: 0.5,
	SETTING_SLEEPING_TIME_THRESHOLD: 1.0,
	SETTING_DISABLE_SLEEPING: false,
	SETTING_LINEAR_SLOP: 0.005,
	SETTING_ANGULAR_SLOP: 0.017453292519943278,

	MAT3_NUM_CREATIONS: 0,
	MAT4_NUM_CREATIONS: 0,
	QUAT_NUM_CREATIONS: 0,
	POSITIVE_INFINITY: Number.POSITIVE_INFINITY,
	NEGATIVE_INFINITY: Number.NEGATIVE_INFINITY,
	PI: 3.14159265358979,
	TWO_PI: 6.28318530717958,
	HALF_PI: 1.570796326794895,
	TO_RADIANS: 0.017453292519943278,
	TO_DEGREES: 57.29577951308238,

};


export {
	CONSTANT,
	SIMULATE_STATE,
	GEOMETRY_TYPE,
	JOINT_TYPE,
	RIGID_BODY_TYPE,
	BROAD_PHASE_TYPE,
	BVH_INSERTION_STRATEGY,
	EPA_POLYHEDRON_STATE,
	GJK_EPA_RESULT_STATE,
	POSITION_CORRECTION_ALGORITHM,
	JACOBIAN_ROW_BIT,
	CONSTRAINT_SOLVER_TYPE,
};